language: python

python:
  - 2.6
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

install:
  - pip install -r requirements_dev.txt
  - python setup.py install

script: py.test testing/

#branches:
#  only:
#    - master
